/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package automatmp1;

import java.util.ArrayList;
import java.awt.Color;
import javax.swing.DefaultListModel;
/**
 *
 * @author Belle
 */
public class Frame extends javax.swing.JFrame {
    Formatter formatter = new Formatter();
    ArrayList<Earth> earth;
    ArrayList<Mars> mars;
    DefaultListModel dm = new DefaultListModel();
    DefaultListModel dm1 = new DefaultListModel();
    DefaultListModel dm2 = new DefaultListModel();
    Entity s = new Entity("Scientist", "Earth");
    Entity c = new Entity("Cow", "Earth");
    Entity l = new Entity("Lion", "Earth");
    Entity g = new Entity("Grains", "Earth");
    Entity h1 = new Entity("Human 1", "Earth");
    Entity h2 = new Entity("Human 2", "Earth");
    int m = 0;
    
    /**
     * Creates new form Frame
     */
    Entity e = new Entity("Scientist", "Earth");
    public Frame() {
        initComponents();
//        Entity s = new Entity("Scientist", "Earth");
//        Entity c = new Entity("Cow", "Earth");
//        Entity l = new Entity("Lion", "Earth");
//        Entity g = new Entity("Grains", "Earth");
//        Entity h1 = new Entity("Human 1", "Earth");
//        Entity h2 = new Entity("Human 2", "Earth");
        jList1.setModel(dm);
        dm.addElement(s.name);
        dm.addElement(c.name);
        dm.addElement(l.name);
        dm.addElement(g.name);
        dm.addElement(h1.name);
        dm.addElement(h2.name);
    //    formatter.appendToPane(jTextPane1, s.name, Color.blue);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sButton = new javax.swing.JButton();
        cButton = new javax.swing.JButton();
        lButton = new javax.swing.JButton();
        gButton = new javax.swing.JButton();
        h1Button = new javax.swing.JButton();
        h2Button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        goButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        clrButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sButton.setText("Scientist");
        sButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sButtonActionPerformed(evt);
            }
        });

        cButton.setText("Cow");
        cButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cButtonActionPerformed(evt);
            }
        });

        lButton.setText("Lion");
        lButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lButtonActionPerformed(evt);
            }
        });

        gButton.setText("Grain");
        gButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gButtonActionPerformed(evt);
            }
        });

        h1Button.setText("Human 1");
        h1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h1ButtonActionPerformed(evt);
            }
        });

        h2Button.setText("Human 2");
        h2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h2ButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Earth");

        jLabel2.setText("Mars");

        goButton.setText("Go");
        goButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goButtonActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(jList1);

        jScrollPane4.setViewportView(jList2);

        jScrollPane5.setViewportView(jList3);

        clrButton.setText("Clear");
        clrButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clrButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(gButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(goButton)
                            .addComponent(h1Button))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(h2Button)
                            .addComponent(clrButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(119, 119, 119)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(225, 225, 225)
                                .addComponent(sButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lButton)))
                        .addGap(136, 136, 136)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(102, 102, 102))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                        .addComponent(jScrollPane3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sButton)
                    .addComponent(cButton)
                    .addComponent(lButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gButton)
                    .addComponent(h1Button)
                    .addComponent(h2Button))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(goButton)
                    .addComponent(clrButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sButtonActionPerformed
        // TODO add your handling code here:
    //    formatter.appendToPane(jTextPane1, e.name, Color.blue);
        jList1.setModel(dm);
        jList2.setModel(dm1);
        jList3.setModel(dm2);
        
        if(dm1.size() < 3){
            dm1.addElement(s.name);
        }
    }//GEN-LAST:event_sButtonActionPerformed

    private void lButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lButtonActionPerformed
        // TODO add your handling code here:
        jList1.setModel(dm);
        jList2.setModel(dm1);
        jList3.setModel(dm2);
        
        if(dm1.size() < 3){
            dm1.addElement(l.name);
        }
    }//GEN-LAST:event_lButtonActionPerformed

    private void cButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cButtonActionPerformed
        // TODO add your handling code here:
        jList1.setModel(dm);
        jList2.setModel(dm1);
        jList3.setModel(dm2);
        
        if(dm1.size() < 3){
            dm1.addElement(c.name);
        }
    }//GEN-LAST:event_cButtonActionPerformed

    private void gButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gButtonActionPerformed
        // TODO add your handling code here:
        jList1.setModel(dm);
        jList2.setModel(dm1);
        jList3.setModel(dm2);
        
        if(dm1.size() < 3){
            dm1.addElement(g.name);
        }
    }//GEN-LAST:event_gButtonActionPerformed

    private void h1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h1ButtonActionPerformed
        // TODO add your handling code here:
        jList1.setModel(dm);
        jList2.setModel(dm1);
        jList3.setModel(dm2);
        
        if(dm1.size() < 3){
            dm1.addElement(h1.name);
        }
    }//GEN-LAST:event_h1ButtonActionPerformed

    private void h2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h2ButtonActionPerformed
        // TODO add your handling code here:
        jList1.setModel(dm);
        jList2.setModel(dm1);
        jList3.setModel(dm2);
        
        if(dm1.size() < 3){
            dm1.addElement(h2.name);
        }
    }//GEN-LAST:event_h2ButtonActionPerformed

    private void goButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goButtonActionPerformed
        // TODO add your handling code here:
        jList1.setModel(dm);
        jList2.setModel(dm1);
        jList3.setModel(dm2);
        int g = 0;
        for(int i = 0; i < dm1.size(); i++){
            if(dm1.get(i).equals("Scientist")){
                g = 1;
            }
        }
        System.out.println("g = " + g);
        if(g == 1){
            if(m % 2 == 0){
                for(int i = 0; i < dm.size(); i++){
                    for(int j = 0; j < dm1.size(); j++){
                        if(dm.get(i).equals(dm1.get(j))){
                            dm.removeElement(dm.get(i));
                        }
                    }
                }

                for(int i = 0; i < dm1.size(); i++){
                    dm2.addElement(dm1.get(i));
                }
                for(int i = 0; i < 3; i++){
                    if(dm1.size() > 0){
                        dm1.removeElement(dm1.get(0));
                    }
                }
                m = m + 1;
            
            }
            
            else{
               for(int i = 0; i < dm2.size(); i++){
                    for(int j = 0; j < dm1.size(); j++){
                        if(dm2.get(i).equals(dm1.get(j))){
                            dm2.removeElement(dm2.get(i));
                        }
                    }
                    
                    
                }
               for(int i = 0; i < dm1.size(); i++){
                    dm.addElement(dm1.get(i));
                }
               
               for(int i = 0; i < 3; i++){
                   if(dm1.size() > 0){
                        dm1.removeElement(dm1.get(0));
                   }
                }
               
               m = m + 1;
            }
        }
    }//GEN-LAST:event_goButtonActionPerformed

    private void clrButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clrButtonActionPerformed
        // TODO add your handling code here:
        jList1.setModel(dm);
        jList2.setModel(dm1);
        jList3.setModel(dm2);
        
        for(int i = 0; i < 3; i++){
                dm1.removeElement(dm1.get(0));
            }
    }//GEN-LAST:event_clrButtonActionPerformed

    public boolean decider(Entity e1, Entity e2, Entity e3){
        if(e1.name.equalsIgnoreCase("Lion")){
            
        }
        return true;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cButton;
    private javax.swing.JButton clrButton;
    private javax.swing.JButton gButton;
    private javax.swing.JButton goButton;
    private javax.swing.JButton h1Button;
    private javax.swing.JButton h2Button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jList3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton lButton;
    private javax.swing.JButton sButton;
    // End of variables declaration//GEN-END:variables
}
